[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
restartPolicyType = "ON_FAILURE"

[[services]]
name = "zazaki-quiz-web"
startCommand = "npm start"

[[services]]
name = "zazaki-quiz-cron"
buildCommand = "npx prisma generate"
startCommand = "npm run cron:daily"
cronSchedule = "0 8 * * *"
restartPolicyType = "NEVER"
